Project project_name {
  database_type: 'PostgreSQL'
  Note: 'Goang API DB'
}

Table driver {
  email varchar(70) [pk, not null]
  id integer [unique, not null, increment]
  username varchar(50) [not null]
  password varchar(100) [not null]
  img_url varchar(120)
  route route_number [not null]
}

Table client {
  username varchar(50) [not null]
  email varchar(70) [pk, not null]
  password varchar(100) [not null]
  img_url varchar(120)
}

Table driver_session {
  id integer [pk, not null, increment]
  email varchar(70) [not null]
  token varchar(250) [not null]
}

Table client_session {
  id integer [pk, not null, increment]
  email varchar(70) [not null]
  token varchar(250) [not null]
}

enum route_number {
  "01"
  "02"
  "03"
  "04"
  "05"
  "06"
  "07"
  "08"
  "09"
  "10"
}

Table route {
  route_num route_number [pk, not null]
  description varchar(400)
  route_point JSONB
}

Ref : route.route_num < driver.route
Ref : driver.email < driver_session.email
Ref : client.email < client_session.email