import dotenv from "dotenv"
dotenv.config()

const POSTGRESQL_HOST = process.env.POSTGRESQL_HOST
const POSTGRESQL_PORT = process.env.POSTGRESQL_PORT
const POSTGRESQL_USERNAME = process.env.POSTGRESQL_USERNAME
const POSTGRESQL_PASSWORD = process.env.POSTGRESQL_PASSWORD
const POSTGRESQL_DB = process.env.POSTGRESQL_DB

export { 
  POSTGRESQL_HOST,
  POSTGRESQL_PORT,
  POSTGRESQL_USERNAME,
  POSTGRESQL_PASSWORD,
  POSTGRESQL_DB
}