import dotenv from "dotenv"
dotenv.config()

const POSTGRESQL_HOST = process.env.POSTGRESQL_HOST
const POSTGRESQL_PORT = process.env.POSTGRESQL_PORT
const POSTGRESQL_USERNAME = process.env.POSTGRESQL_USERNAME
const POSTGRESQL_PASSWORD = process.env.POSTGRESQL_PASSWORD
const POSTGRESQL_DB = process.env.POSTGRESQL_DB
const JWT_SECRET_DRIVER = process.env.JWT_SECRET_DRIVER
const JWT_SECRET_CLIENT = process.env.JWT_SECRET_CLIENT
const LIVE_URL = process.env.LIVE_URL

export { 
  POSTGRESQL_HOST,
  POSTGRESQL_PORT,
  POSTGRESQL_USERNAME,
  POSTGRESQL_PASSWORD,
  POSTGRESQL_DB,
  JWT_SECRET_DRIVER,
  JWT_SECRET_CLIENT,
  LIVE_URL
}